import type { Metadata } from "next";
import "./globals.css";
import { cookies } from 'next/headers';
import Sidebar from './components/Sidebar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const sessionUser = cookieStore.get('session_user')
  let user = null

  if (sessionUser) {
    try {
      user = JSON.parse(sessionUser.value)
    } catch (e) {
      // ignore
    }
  }

  return (
    <html lang="en">
      <body style={{ display: 'flex', minHeight: '100vh', margin: 0 }}>
        {user && <Sidebar user={user} />}
        <main style={{ flex: 1, backgroundColor: '#fff' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
