import type { Metadata } from "next";
import "./globals.css";
import { cookies } from 'next/headers';
import Sidebar from './components/Sidebar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const sessionUser = cookieStore.get('session_user')
  let user = null

  if (sessionUser) {
    try {
      user = JSON.parse(sessionUser.value)
    } catch (e) {
      // ignore
    }
  }

  return (
    <html lang="en">
      <body className={`min-h-screen bg-cream ${poppins.className}`}>
        {user && <Sidebar user={user} />}
        <main className={`bg-cream ${user ? 'ml-[280px]' : ''}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
